### ISSUE TITLE
analyze flag tags optional

### ISSUE THREAD

**Issue by Deleplace** [eliben/so-tag-sentiment-analysis#3]
It would be nice the let to user omit the command-line flag "tags", meaning "analyze all the tags we have locally, no tag constraint".

**Comment by Deleplace** [comment]
This probably involves restructuring a loop to feed a map with arbitrary tags found in the data.
Or, make a first pass in the data dir beforehand to discover the tags.

Shall I?

**Comment by eliben** [comment]
The "discovery" process is simple because each tag has its own directory the data is pulled into.

No objections to adding this unless it becomes too complicated (but I don't think it should).
